language: android
cache: false
sudo: true
branches:
  only:
  - master

env:
  global:
    - DIR=EspolguideDev # Project directory
    - ANDROID_API_LEVEL=27
    - ANDROID_EMULATOR_LEVEL=18
    - ANDROID_BUILD_TOOLS_VERSION=26.0.2
    #- ANDROID_HOME=${TRAVIS_BUILD_DIR}/android-sdk
   # - ANDROID_HOME=/usr/local/android-sdk
   # - TOOLS=${ANDROID_HOME}/tools
    #- PATH=${ANDROID_HOME}:${ANDROID_HOME}/emulator:${TOOLS}:${TOOLS}/bin:${ANDROID_HOME}/platform-tools:${PATH}
    - GRADLE_USER_HOME="${TRAVIS_BUILD_DIR}/gradle"
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - tools
    - platform-tools

    # The BuildTools version used by your project
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION

    # The SDK version used to compile your project
    - android-$ANDROID_API_LEVEL

    # Additional components
    - extra-google-google_play_services
    - extra-android-support
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-$ANDROID_API_LEVEL

licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

before_script:
    - mkdir "$ANDROID_HOME/licenses" || true
    #- cp ./licenses/* "$ANDROID_HOME/licenses/"

#install:
  #- cd ${TRAVIS_BUILD_DIR}/${DIR} && ./gradlew clean build

script:
    #- gradle build connectedCheck  
  - ./gradlew connectedCheck

after_script:
  # Show tests and lint results
  - cat ${TRAVIS_BUILD_DIR}/${DIR}/*/build/outputs/androidTest-results/connected/*
  - cat ${TRAVIS_BUILD_DIR}/${DIR}/*/build/reports/lint-results.xml

notifications:
  email:
    - mguarand@espol.edu.ec

