language: android
cache: false
jdk: oraclejdk8
sudo: true
branches:
  only:
  - master

env:
  global:
    - DIR=EspolguideDev # Project directory
    - ANDROID_API_LEVEL=27
    - ANDROID_EMULATOR_LEVEL=18
    - ANDROID_BUILD_TOOLS_VERSION=26.0.1
    #- ANDROID_HOME=${TRAVIS_BUILD_DIR}/android-sdk
   # - ANDROID_HOME=/usr/local/android-sdk
   # - TOOLS=${ANDROID_HOME}/tools
    #- PATH=${ANDROID_HOME}:${ANDROID_HOME}/emulator:${TOOLS}:${TOOLS}/bin:${ANDROID_HOME}/platform-tools:${PATH}
   # - GRADLE_USER_HOME="${TRAVIS_BUILD_DIR}/gradle"

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - tools
    - tools
    - platform-tools

    # The BuildTools version used by your project
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION

    # The SDK version used to compile your project
    - android-$ANDROID_API_LEVEL

    # Additional components
    - extra-google-google_play_services
    - extra-android-support
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-$ANDROID_API_LEVEL

licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
    - '.+'

before_install:
  - chmod +x gradlew

install:
  - sdkmanager --list || true # List all available targets, device definitions and AVDs.
  # Update sdk tools to latest version and install/update components
  - echo yes | sdkmanager "tools"
  - echo yes | sdkmanager "platform-tools"
  - echo yes | sdkmanager "build-tools;"$ANDROID_BUILD_TOOLS_VERSION
  - echo yes | sdkmanager "platforms;android-"$ANDROID_API_LEVEL # Latest platform required by SDK tools

  - echo yes | sdkmanager "extras;android;m2repository"
  - echo yes | sdkmanager "extras;google;m2repository"
  - echo yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout;1.0.2"
  - echo yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout-solver;1.0.2"

  - echo yes | sdkmanager --update
  - echo yes | sdkmanager --licenses

  # Check components status
- sdkmanager --list || true

before_script:
  - mkdir -p "$ANDROID_HOME/licenses"
    #- cp ./licenses/* "$ANDROID_HOME/licenses/"

script:
    #- gradle build connectedCheck  
  - ./gradlew connectedCheck
  - ./gradlew lint

after_script:
  # Show tests and lint results
  - echo $ANDROID_TARGET
  - cat ${TRAVIS_BUILD_DIR}/${DIR}/*/build/outputs/androidTest-results/connected/*
  - cat ${TRAVIS_BUILD_DIR}/${DIR}/*/build/reports/lint-results.xml

notifications:
  email:
    - mguarand@espol.edu.ec

